name: Build ESPHome Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile firmware
        run: |
          mkdir -p build_output
          esphome compile esphome/voiceassistant.yaml
          cp .pioenvs/voiceassistant/firmware.bin output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4   # Đã cập nhật từ v3 -> v4
        with:
          name: voiceassistant-firmware
          path: build_output/voiceassistant.bin
