name: Build ESPHome Firmware

on:
  workflow_dispatch: # Chạy thủ công
  push:
    branches:
      - main         # Tự build khi push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile firmware
        run: |
          mkdir -p build_output
          esphome compile esphome/voiceassistant.yaml
          cp .esphome/build/*/firmware.bin build_output/voiceassistant.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: voiceassistant-firmware
          path: build_output/voiceassistant.bin
